server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka: #将服务注册至服务中心
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** #将商品微服务映射到/item/**中
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false #默认为true 设置为false 避免自动修改路径
  retryable: true
  ignored-services: upload-service #忽略upload-service服务 绕过网关
ribbon:
  ConnectTimeout: 6000 # 连接超时时间(ms)
  ReadTimeout: 6000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1
  secure-ports: # 同一实例的重试次数
    eureka:
      enable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms